<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="soccer_bot">

    <xacro:property name="chassis_mass" value="1.5"/> <xacro:property name="chassis_width" value="0.15"/> <xacro:property name="chassis_length" value="0.15"/> <xacro:property name="chassis_height" value="0.20"/> <material name="blue">
        <color rgba="0 0 0.8 1"/>
    </material>

    <link name="base_link">
    </link>

    <link name="chassis">
        <visual>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        
        <collision>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>

        <inertial>
            <mass value="${chassis_mass}"/>
            <inertia ixx="${(1/12) * chassis_mass * (chassis_height*chassis_height + chassis_width*chassis_width)}" 
                     ixy="0.0" ixz="0.0" 
                     iyy="${(1/12) * chassis_mass * (chassis_length*chassis_length + chassis_height*chassis_height)}" 
                     iyz="0.0" 
                     izz="${(1/12) * chassis_mass * (chassis_length*chassis_length + chassis_width*chassis_width)}"/>
        </inertial>
    </link>

    <joint name="base_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="0 0 ${chassis_height/2 + 0.02}"/> </joint>
<xacro:property name="wheel_radius" value="0.035"/> <xacro:property name="wheel_width" value="0.02"/>   <xacro:property name="wheel_mass" value="0.1"/>     <xacro:macro name="wheel_maker" params="prefix location_y">
        
        <link name="${prefix}_wheel">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
                <material name="black">
                    <color rgba="0 0 0 1"/>
                </material>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
            </collision>
            <inertial>
                <mass value="${wheel_mass}"/>
                <inertia ixx="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}" 
                         ixy="0" ixz="0" 
                         iyy="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}" 
                         iyz="0" 
                         izz="${(1/2) * wheel_mass * (wheel_radius*wheel_radius)}"/>
            </inertial>
        </link>

        <joint name="${prefix}_wheel_joint" type="continuous">
            <parent link="base_link"/>
            <child link="${prefix}_wheel"/>
            <origin xyz="0 ${location_y} ${wheel_radius}" rpy="-${pi/2} 0 0"/>
            <axis xyz="0 0 1"/> </joint>
    </xacro:macro>

    <xacro:wheel_maker prefix="left" location_y="${chassis_width/2 + 0.015}"/>
    
    <xacro:wheel_maker prefix="right" location_y="-${chassis_width/2 - 0.015}"/>


    <link name="caster_wheel">
        <visual>
            <geometry>
                <sphere radius="${wheel_radius/2}"/>
            </geometry>
            <material name="white">
                <color rgba="1 1 1 1"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius/2}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.05"/>
            <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
        </inertial>
    </link>

    <joint name="caster_joint" type="fixed">
        <parent link="base_link"/>
        <child link="caster_wheel"/>
        <origin xyz="0.06 0 ${wheel_radius/2}"/>
    </joint>

<gazebo reference="chassis">
        <material>Gazebo/Blue</material>
    </gazebo>
    <gazebo reference="left_wheel">
        <material>Gazebo/Black</material>
    </gazebo>
    <gazebo reference="right_wheel">
        <material>Gazebo/Black</material>
    </gazebo>
    <gazebo reference="caster_wheel">
        <material>Gazebo/White</material>
        <mu1>0.001</mu1>
        <mu2>0.001</mu2>
    </gazebo>

    <gazebo>
        <plugin filename="gz-sim-diff-drive-system" name="gz::sim::systems::DiffDrive">
            
            <left_joint>left_wheel_joint</left_joint>
            <right_joint>right_wheel_joint</right_joint>

            <wheel_separation>${chassis_width + wheel_width}</wheel_separation>
            <wheel_radius>${wheel_radius}</wheel_radius>

            <max_linear_acceleration>1</max_linear_acceleration>
            <min_linear_acceleration>-1</min_linear_acceleration>
            
            <topic>cmd_vel</topic> <odom_topic>odom</odom_topic> <tf_topic>tf</tf_topic>
            <frame_id>odom</frame_id>
            <child_frame_id>base_link</child_frame_id>
            <odom_publish_frequency>30</odom_publish_frequency>
        </plugin>
    </gazebo>

</robot>
