<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="mcsoccer">

    <xacro:property name="chassis_mass" value="1.3"/> 
    <xacro:property name="chassis_width" value="0.15"/> 
    <xacro:property name="chassis_length" value="0.15"/> 
    <xacro:property name="chassis_height" value="0.165"/> 
    <xacro:property name="wheel_radius" value="0.035"/> 
    <xacro:property name="wheel_width" value="0.02"/>   
    <xacro:property name="wheel_mass" value="0.1"/>
    <xacro:property name="wheel_offset_y" value="${chassis_width/2 + 0.015}"/>

    <material name="blue"> <color rgba="0 0 0.8 1"/> </material>
    <material name="black"> <color rgba="0 0 0 1"/> </material>
    <material name="white"> <color rgba="1 1 1 1"/> </material>

    <xacro:macro name="box_inertia" params="m x y z">
        <inertial>
            <mass value="${m}"/>
            <inertia ixx="${(m/12) * (y*y + z*z)}" ixy="0" ixz="0"
                     iyy="${(m/12) * (x*x + z*z)}" iyz="0"
                     izz="${(m/12) * (x*x + y*y)}"/>
        </inertial>
    </xacro:macro>

    <xacro:macro name="cylinder_inertia" params="m r h">
        <inertial>
            <mass value="${m}"/>
            <inertia ixx="${(m/12) * (3*r*r + h*h)}" ixy="0" ixz="0"
                     iyy="${(m/12) * (3*r*r + h*h)}" iyz="0"
                     izz="${(m/2) * (r*r)}"/>
        </inertial>
    </xacro:macro>

    <xacro:macro name="sphere_inertia" params="m r">
        <inertial>
            <mass value="${m}"/>
            <inertia ixx="${(2/5) * m * (r*r)}" ixy="0" ixz="0"
                     iyy="${(2/5) * m * (r*r)}" iyz="0"
                     izz="${(2/5) * m * (r*r)}"/>
        </inertial>
    </xacro:macro>

    <link name="base_link"></link>

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="0 0 ${chassis_height/2 + 0.02}"/> 
    </joint>

    <link name="chassis">
        <visual>
            <geometry> <box size="${chassis_length} ${chassis_width} ${chassis_height}"/> </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry> <box size="${chassis_length} ${chassis_width} ${chassis_height}"/> </geometry>
        </collision>
        <xacro:box_inertia m="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}"/>
    </link>

    <xacro:macro name="wheel" params="prefix reflect">
        <link name="${prefix}_wheel">
            <visual>
                <geometry> <cylinder radius="${wheel_radius}" length="${wheel_width}"/> </geometry>
                <material name="black"/>
            </visual>
            <collision>
                <geometry> <cylinder radius="${wheel_radius}" length="${wheel_width}"/> </geometry>
            </collision>
            <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}"/>
        </link>

        <joint name="${prefix}_wheel_joint" type="continuous">
            <parent link="base_link"/>
            <child link="${prefix}_wheel"/>
            <origin xyz="0 ${reflect * wheel_offset_y} ${wheel_radius}" rpy="-${pi/2} 0 0"/>
            <axis xyz="0 0 1"/> 
        </joint>
    </xacro:macro>

    <xacro:wheel prefix="left" reflect="1"/>
    <xacro:wheel prefix="right" reflect="-1"/>

    <link name="caster_wheel">
        <visual>
            <geometry> <sphere radius="${wheel_radius/2}"/> </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry> <sphere radius="${wheel_radius/2}"/> </geometry>
        </collision>
        <xacro:sphere_inertia m="0.05" r="${wheel_radius/2}"/>
    </link>

    <joint name="caster_joint" type="fixed">
        <parent link="chassis"/> 
        <child link="caster_wheel"/>
        <origin xyz="0.06 0 -${chassis_height/2 + 0.02 - (wheel_radius/2)}"/>
    </joint>

    <xacro:include filename="mcsoccer.gazebo" />

</robot>